### ISSUE TITLE
Wine applications in guest mode

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#614] opened 2023-01-14 10:50 UTC
Hi,
in Magdeburg a lot of schools are using the application Fuxnoten to write the school reports. Fuxnoten is a Windows application.

We have the following setting. The Fuxnoten application to write the school reports is on an usb stick in a crypted folder. The encryption is done with Cryptomator. Cryptomator should be on every Puavo laptop ... it's configured for all devices in Magdeburg. When the Fuxnoten folder is decrypted then the user should start the Fuxnoten application from this folder.

I tested it with some test accounts on different Puavo devices. Yes, it works fine and it's great!

When I try to start the Fuxnoten application in guest mode it does not work. Is this an issue for the guest mode? I think that currently no Windows application will start in guest mode. Or is this a feature because nobody should be able to run Windows applications in guest mode?

Best regards,
Ralf

**Comment by Mazhoon** [comment] 2023-01-14 10:58
In general they definitely should, and in my experience, do work. (I do most of my Wine-related testing on guest account, to get a fresh testing environment with re-login.) If it's only Fuxnoten and other software run from USB sticks, my initial guess would be that it's somehow related to decrypted folder's or USB stick's permissions (these are cases I don't think I have ever tested running Wine on).

**Comment by ralf-krause** [comment] 2023-01-14 12:29
I started Puavo in guest mode again. I put in the stick and decrypted the folder. I moved the decrypted folder to the Puavo desktop. Then I tried to start the Fuxnoten application from the desktop ... not from the Cryptomator device. The Wine application loaded some things from anywhere to configure itself. And then I got an error message "Error: No files to zip!".

When I logged in with any demo user the Fuxnoten application starts with Wine from the desktop or from the decrypted Cryptomator folder on the usb stick. It works and there seems to be no problem.

I you want to test the demo files yourself you can download and try it. The Cryptomator password is 1234567ABC.

**Comment by Mazhoon** [comment] 2023-01-14 14:23
Okay, thank you! I can reproduce as described. Interesting. I didn't yet see an explanation for this, but I'll have a deeper look later.

**Comment by Mazhoon** [comment] 2023-01-27 11:44
Okay, I inspected more. On a real account,
Erfassungsmodul_01A/erfassungsmodul_fuxmedia.exe: "Error - no files to zip!"
Erfassungsmodul_02A/erfassungsmodul_fuxmedia.exe: Starts and everything seems ok.
On guest account
Erfassungsmodul_01A/erfassungsmodul_fuxmedia.exe: "Error - no files to zip!"
Erfassungsmodul_02A/erfassungsmodul_fuxmedia.exe: Starts and everything seems ok.

**Comment by Mazhoon** [comment] 2023-08-14 05:32
Closing this one, as based on my tests (previous message) the problem was not related to guest account, but one test dataset being functional (on both guest and normal accounts) and one not working with either. Please do comment if you observe any different behaviour.

**Closed as completed by Mazhoon** 2023-08-14 05:32 UTC
