### ISSUE TITLE
Gdm password field behaviour when wrong pw is entered

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#369] opened 2018-04-04 12:06 UTC
In case user misstypes the password in the gdm it displays an error message and at the same time the password field is active. In such a case the user usually starts retyping the password but while doing it the field is changed as username field. This causes the accident where the password is visible on the screen.

**Comment by jarmopi** [comment] 2018-04-19 06:02
Should be fixed by 83598b38732338bf8ca5c2c213c03510e65bad91. The relevant change is `gdm/util.js`. I couldn't reproduce the bug after this change.

**Closed by jarmopi** 2018-04-19 06:02 UTC
