### ISSUE TITLE
NFS mount hangs on some strange situation on fatclients

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#240] opened 2017-05-18 10:34 UTC
Setting NFS unique id might solve the problem.

**Comment by juhaerk** [comment] 2017-05-18 10:37
Setting nfs.nfs4_unique_id=bb975d9b-9185-4980-8d4d-2e1d55d2fb55 (uuidgen) on a kernel command line (each boot having its own special id) appears to solve this issue, but some more testing is needed.

**Comment by asokero** [comment] 2017-07-07 08:18
/var/log/syslog
```Jul  7 10:47:21 toimisto-debian-folio gdm-password]: Libgcrypt warning: missing initialization - please fix the application
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: Key table file '/etc/krb5.keytab' not found while beginning keytab scan for keytab 'FILE:/etc/krb5.keytab'
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: Key table file '/etc/krb5.keytab' not found while beginning keytab scan for keytab 'FILE:/etc/krb5.keytab'
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: Key table file '/etc/krb5.keytab' not found while beginning keytab scan for keytab 'FILE:/etc/krb5.keytab'
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: Key table file '/etc/krb5.keytab' not found while beginning keytab scan for keytab 'FILE:/etc/krb5.keytab'
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: Key table file '/etc/krb5.keytab' not found while beginning keytab scan for keytab 'FILE:/etc/krb5.keytab'
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: Key table file '/etc/krb5.keytab' not found while beginning keytab scan for keytab 'FILE:/etc/krb5.keytab'
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: gssd_refresh_krb5_machine_credential: no usable keytab entry found in keytab /etc/krb5.keytab for connection with host homedir
.toimisto.opinsys.fi
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: No credentials found for connection to server homedir.toimisto.opinsys.fi
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: Key table file '/etc/krb5.keytab' not found while beginning keytab scan for keytab 'FILE:/etc/krb5.keytab'
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: Key table file '/etc/krb5.keytab' not found while beginning keytab scan for keytab 'FILE:/etc/krb5.keytab'
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: Key table file '/etc/krb5.keytab' not found while beginning keytab scan for keytab 'FILE:/etc/krb5.keytab'
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: Key table file '/etc/krb5.keytab' not found while beginning keytab scan for keytab 'FILE:/etc/krb5.keytab'
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: Key table file '/etc/krb5.keytab' not found while beginning keytab scan for keytab 'FILE:/etc/krb5.keytab'
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: Key table file '/etc/krb5.keytab' not found while beginning keytab scan for keytab 'FILE:/etc/krb5.keytab'
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: gssd_refresh_krb5_machine_credential: no usable keytab entry found in keytab /etc/krb5.keytab for connection with host homedir
.toimisto.opinsys.fi
Jul  7 10:47:21 toimisto-debian-folio rpc.gssd[1791]: ERROR: No credentials found for connection to server homedir.toimisto.opinsys.fi
Jul  7 10:47:21 toimisto-debian-folio systemd[1]: Created slice User Slice of asokero.
```

**Comment by juhaerk** [comment] 2017-07-27 10:35
Let's try if this works: b3631599a6928ee21355b462bd18ef3ef57646ee.  Closing for now, but issues may persist, because they are hard to reproduce.  We'll see...

**Closed by juhaerk** 2017-07-27 10:35 UTC
