### ISSUE TITLE
Connecting to WPA2 Enterprise wlan requires a root password

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#515] opened 2019-12-23 07:11 UTC
Users cannot connect to WPA2 enterprise network, as Gnome Network UI always asks for root password. Adding user to netdev group does not solve this issue.

**Comment by juhaerk** [comment] 2019-12-30 14:50
This is not exactly true. What does not work is that it is not possible to make a user-specific WPA-EAP network configuration through the Gnome UI. This is not possible in the more usual WPA-PSK case either without this patch that we have: https://github.com/puavo-org/puavo-os/blob/master/debs/gnome-shell/debian/patches/99-make-private-network-connections-possible.patch .  This patch however is not effective in the WPA-EAP case.

What works, however, is creating WPA-EAP network configuration as a primary user (or at least it worked for me), because that user has permissions to create system-wide network settings.

I am not sure whether we should try to fix this (soonish), sure it would be nice, but in case we manage to fix #516 that should cover maybe all use cases?

**Comment by Mazhoon** [comment] 2024-05-30 08:26
Bookworm:
Problem 1: nothing happens when clicking WPA2 Enterprise network in gnome shell wifi selector.
Problem 2: network can be set in gnome control center, but trying to save it causes sysadmin auth dialog to pop up.

**Comment by Mazhoon** [comment] 2024-06-04 08:40
Problem 1 also happens on Bullseye.
~~Running dbus-monitor manually in lg shows the error for launchSettingsPanel('wifi', 'connect-8021x-wifi', this._getDeviceDBusPath(), ap.get_path()): "The name org.gnome.Settings was not provided by any .service files"
Seems to be a long-standing gnome bug (both bullseye and bookworm). Changing the dbus call to org.gnome.ControlCenter (as suggested by later changes at https://gitlab.gnome.org/GNOME/gnome-control-center/-/commit/acd59aec6560620ca9d27a21eba6c9ab15569e53 ) seems to fix opening the settings panel. However, this doesn't make that much sense as the appid has been changed in the code only after bullseye. When clicking the UI button on bullseye, nothing is visible on dbus-monitor.~~
Verified to be broken on vanilla bullseye, too. And Fedora 38, and 39, and 40 (=Gnome 46). Nothing in dbus-monitor.

Reported upstream at https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7698

**Comment by Mazhoon** [comment] 2024-07-25 07:19
Found the cause, merge request upstream at https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3426

**Comment by Mazhoon** [comment] 2024-07-25 07:37
Fixed with https://github.com/puavo-org/puavo-os/commit/ca9cb1d413c0222e9547d93658212c08c5baddcb

**Closed by Mazhoon** 2024-07-25 07:37 UTC
Labels: Bookworm
