### ISSUE TITLE
puavo-pulseaudio-get-puavoconf does not work on Bookworm

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#662] opened 2024-03-01 10:10 UTC
```
:~$ puavo-pulseaudio-get-puavoconf
Could not determine the default sink!
Could not determine the default source!
```

**Comment by sarrchri** [comment] 2024-03-07 08:00
Just in case, I tested that this indeed does not happen on Bullseye, so it is Bookworm specific.
The issue was caused by `pactl info` output being automatically localized to the session/system language.

Fixed as of commit 0c4602e.

**Closed as completed by sarrchri** 2024-03-07 08:00 UTC
Labels: Bookworm
